NUM_CHROM_IN_POPULATION: int = 6
DESTINED_YIELD_RATE: float = 0.9
MAX_GENERATION: int = 100 

SELECTION_PROB: float = 0.5

GENE_B_MUTATION_PROB: float = 0.1
GENE_B_MUTATION_LOCUS_RATIO: float = 0.1

GENE_P_MUTATION_PROB: float = 0.1
GENE_P_MUTATION_LOCUS_RATIO: float = 0.1